project_id = "ibospodoxgumgmjymgtm"

[functions.support-chat]
verify_jwt = false

[functions.scrape-price-list]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
